### ISSUE TITLE
Parsing does not conform to the ABNF in RFC4288

### ISSUE THREAD

**Issue by mjc** [camshaft/mimetype_parser#2]
RFC4288 section 4.2 says this is the ABNF for mime types:

```
   Type and subtype names MUST conform to the following ABNF:

       type-name = reg-name
       subtype-name = reg-name

       reg-name = 1*127reg-name-chars
       reg-name-chars = ALPHA / DIGIT / "!" /
                       "#" / "$" / "&" / "." /
                       "+" / "-" / "^" / "_"
```

This should allow multiple + characters, but currently mimetype_parser does not allow this.

For example: `application/vnd.foo+hal+json` should be allowed.

**Comment by camshaft** [comment]
ah i didn't catch that. thanks for bringing that up. not sure when I'll be able to get to it but I do accept PRs :smiley:
